export interface CardTheme {
  id: string;
  name: string;
  bg: string;
  bgHover: string;
  border: string;
  borderHover: string;
  accent: string;
  accentBg: string;
  iconBg: string;
  iconText: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  tagText: string;
  animClass: string;
  buttonPrimary?: string;
  buttonSecondary?: string;
}

export const CARD_PALETTES: Record<string, CardTheme> = {
  emerald: {
    id: 'emerald',
    name: 'Emerald Green',
    bg: 'bg-emerald-50/70',
    bgHover: 'hover:bg-emerald-50/95',
    border: 'border-emerald-200/80',
    borderHover: 'hover:border-emerald-400',
    accent: 'text-emerald-700',
    accentBg: 'bg-emerald-600',
    iconBg: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    iconText: 'text-emerald-700',
    badgeBg: 'bg-emerald-100/90',
    badgeText: 'text-emerald-900',
    badgeBorder: 'border-emerald-200',
    tagText: 'text-emerald-800',
    animClass: 'anim-card-emerald',
    buttonPrimary: 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-700/20',
    buttonSecondary: 'bg-emerald-100/80 hover:bg-emerald-200/90 text-emerald-900 border-emerald-300',
  },
  blue: {
    id: 'blue',
    name: 'Blue',
    bg: 'bg-blue-50/70',
    bgHover: 'hover:bg-blue-50/95',
    border: 'border-blue-200/80',
    borderHover: 'hover:border-blue-400',
    accent: 'text-blue-700',
    accentBg: 'bg-blue-600',
    iconBg: 'bg-blue-100 text-blue-800 border-blue-200',
    iconText: 'text-blue-700',
    badgeBg: 'bg-blue-100/90',
    badgeText: 'text-blue-900',
    badgeBorder: 'border-blue-200',
    tagText: 'text-blue-800',
    animClass: 'anim-card-blue',
    buttonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-700/20',
    buttonSecondary: 'bg-blue-100/80 hover:bg-blue-200/90 text-blue-900 border-blue-300',
  },
  purple: {
    id: 'purple',
    name: 'Purple',
    bg: 'bg-purple-50/70',
    bgHover: 'hover:bg-purple-50/95',
    border: 'border-purple-200/80',
    borderHover: 'hover:border-purple-400',
    accent: 'text-purple-700',
    accentBg: 'bg-purple-600',
    iconBg: 'bg-purple-100 text-purple-800 border-purple-200',
    iconText: 'text-purple-700',
    badgeBg: 'bg-purple-100/90',
    badgeText: 'text-purple-900',
    badgeBorder: 'border-purple-200',
    tagText: 'text-purple-800',
    animClass: 'anim-card-purple',
    buttonPrimary: 'bg-purple-600 hover:bg-purple-700 text-white shadow-purple-700/20',
    buttonSecondary: 'bg-purple-100/80 hover:bg-purple-200/90 text-purple-900 border-purple-300',
  },
  orange: {
    id: 'orange',
    name: 'Orange',
    bg: 'bg-orange-50/70',
    bgHover: 'hover:bg-orange-50/95',
    border: 'border-orange-200/80',
    borderHover: 'hover:border-orange-400',
    accent: 'text-orange-700',
    accentBg: 'bg-orange-600',
    iconBg: 'bg-orange-100 text-orange-800 border-orange-200',
    iconText: 'text-orange-700',
    badgeBg: 'bg-orange-100/90',
    badgeText: 'text-orange-900',
    badgeBorder: 'border-orange-200',
    tagText: 'text-orange-800',
    animClass: 'anim-card-orange',
    buttonPrimary: 'bg-orange-600 hover:bg-orange-700 text-white shadow-orange-700/20',
    buttonSecondary: 'bg-orange-100/80 hover:bg-orange-200/90 text-orange-900 border-orange-300',
  },
  yellow: {
    id: 'yellow',
    name: 'Golden Yellow',
    bg: 'bg-amber-50/70',
    bgHover: 'hover:bg-amber-50/95',
    border: 'border-amber-200/80',
    borderHover: 'hover:border-amber-400',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-600',
    iconBg: 'bg-amber-100 text-amber-900 border-amber-200',
    iconText: 'text-amber-800',
    badgeBg: 'bg-amber-100/90',
    badgeText: 'text-amber-950',
    badgeBorder: 'border-amber-200',
    tagText: 'text-amber-850',
    animClass: 'anim-card-yellow',
    buttonPrimary: 'bg-amber-600 hover:bg-amber-700 text-white shadow-amber-700/20',
    buttonSecondary: 'bg-amber-100/80 hover:bg-amber-200/90 text-amber-950 border-amber-300',
  },
  cyan: {
    id: 'cyan',
    name: 'Cyan',
    bg: 'bg-cyan-50/70',
    bgHover: 'hover:bg-cyan-50/95',
    border: 'border-cyan-200/80',
    borderHover: 'hover:border-cyan-400',
    accent: 'text-cyan-800',
    accentBg: 'bg-cyan-600',
    iconBg: 'bg-cyan-100 text-cyan-900 border-cyan-200',
    iconText: 'text-cyan-800',
    badgeBg: 'bg-cyan-100/90',
    badgeText: 'text-cyan-950',
    badgeBorder: 'border-cyan-200',
    tagText: 'text-cyan-850',
    animClass: 'anim-card-cyan',
    buttonPrimary: 'bg-cyan-600 hover:bg-cyan-700 text-white shadow-cyan-700/20',
    buttonSecondary: 'bg-cyan-100/80 hover:bg-cyan-200/90 text-cyan-950 border-cyan-300',
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    bg: 'bg-rose-50/70',
    bgHover: 'hover:bg-rose-50/95',
    border: 'border-rose-200/80',
    borderHover: 'hover:border-rose-400',
    accent: 'text-rose-700',
    accentBg: 'bg-rose-600',
    iconBg: 'bg-rose-100 text-rose-800 border-rose-200',
    iconText: 'text-rose-700',
    badgeBg: 'bg-rose-100/90',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-200',
    tagText: 'text-rose-800',
    animClass: 'anim-card-rose',
    buttonPrimary: 'bg-rose-600 hover:bg-rose-700 text-white shadow-rose-700/20',
    buttonSecondary: 'bg-rose-100/80 hover:bg-rose-200/90 text-rose-900 border-rose-300',
  },
  teal: {
    id: 'teal',
    name: 'Teal',
    bg: 'bg-teal-50/70',
    bgHover: 'hover:bg-teal-50/95',
    border: 'border-teal-200/80',
    borderHover: 'hover:border-teal-400',
    accent: 'text-teal-800',
    accentBg: 'bg-teal-600',
    iconBg: 'bg-teal-100 text-teal-900 border-teal-200',
    iconText: 'text-teal-800',
    badgeBg: 'bg-teal-100/90',
    badgeText: 'text-teal-950',
    badgeBorder: 'border-teal-200',
    tagText: 'text-teal-850',
    animClass: 'anim-card-teal',
    buttonPrimary: 'bg-teal-600 hover:bg-teal-700 text-white shadow-teal-700/20',
    buttonSecondary: 'bg-teal-100/80 hover:bg-teal-200/90 text-teal-950 border-teal-300',
  },
  indigo: {
    id: 'indigo',
    name: 'Indigo',
    bg: 'bg-indigo-50/70',
    bgHover: 'hover:bg-indigo-50/95',
    border: 'border-indigo-200/80',
    borderHover: 'hover:border-indigo-400',
    accent: 'text-indigo-700',
    accentBg: 'bg-indigo-600',
    iconBg: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    iconText: 'text-indigo-700',
    badgeBg: 'bg-indigo-100/90',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    tagText: 'text-indigo-800',
    animClass: 'anim-card-indigo',
    buttonPrimary: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-indigo-700/20',
    buttonSecondary: 'bg-indigo-100/80 hover:bg-indigo-200/90 text-indigo-900 border-indigo-300',
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    bg: 'bg-slate-100/70',
    bgHover: 'hover:bg-slate-100/95',
    border: 'border-slate-200/90',
    borderHover: 'hover:border-slate-400',
    accent: 'text-slate-800',
    accentBg: 'bg-slate-700',
    iconBg: 'bg-slate-200 text-slate-800 border-slate-300',
    iconText: 'text-slate-800',
    badgeBg: 'bg-slate-200/90',
    badgeText: 'text-slate-900',
    badgeBorder: 'border-slate-300',
    tagText: 'text-slate-800',
    animClass: 'anim-card-slate',
    buttonPrimary: 'bg-slate-700 hover:bg-slate-800 text-white shadow-slate-700/20',
    buttonSecondary: 'bg-slate-200 hover:bg-slate-300 text-slate-900 border-slate-300',
  },
  zinc: {
    id: 'zinc',
    name: 'Zinc',
    bg: 'bg-zinc-100/70',
    bgHover: 'hover:bg-zinc-100/95',
    border: 'border-zinc-200/90',
    borderHover: 'hover:border-zinc-400',
    accent: 'text-zinc-800',
    accentBg: 'bg-zinc-700',
    iconBg: 'bg-zinc-200 text-zinc-800 border-zinc-300',
    iconText: 'text-zinc-800',
    badgeBg: 'bg-zinc-200/90',
    badgeText: 'text-zinc-900',
    badgeBorder: 'border-zinc-300',
    tagText: 'text-zinc-800',
    animClass: 'anim-card-zinc',
    buttonPrimary: 'bg-zinc-700 hover:bg-zinc-800 text-white shadow-zinc-700/20',
    buttonSecondary: 'bg-zinc-200 hover:bg-zinc-300 text-zinc-900 border-zinc-300',
  },
  copper: {
    id: 'copper',
    name: 'Copper',
    bg: 'bg-orange-50/70',
    bgHover: 'hover:bg-orange-50/95',
    border: 'border-amber-300/80',
    borderHover: 'hover:border-amber-500',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-700',
    iconBg: 'bg-amber-100 text-amber-900 border-amber-200',
    iconText: 'text-amber-800',
    badgeBg: 'bg-amber-100/90',
    badgeText: 'text-amber-950',
    badgeBorder: 'border-amber-300',
    tagText: 'text-amber-900',
    animClass: 'anim-card-copper',
    buttonPrimary: 'bg-amber-700 hover:bg-amber-800 text-white shadow-amber-800/20',
    buttonSecondary: 'bg-amber-100/80 hover:bg-amber-200/90 text-amber-950 border-amber-300',
  },
};

export const STAGGER_DELAYS = [
  'delay-stagger-1',
  'delay-stagger-2',
  'delay-stagger-3',
  'delay-stagger-4',
  'delay-stagger-5',
  'delay-stagger-6',
];

export function getStaggerDelay(index: number): string {
  return STAGGER_DELAYS[index % STAGGER_DELAYS.length];
}

export const ROTATING_PALETTE_KEYS = [
  'emerald',
  'blue',
  'purple',
  'orange',
  'yellow',
  'cyan',
  'rose',
  'teal',
  'indigo',
  'slate',
];

export function getCardThemeByIndex(index: number): CardTheme {
  const key = ROTATING_PALETTE_KEYS[index % ROTATING_PALETTE_KEYS.length];
  return CARD_PALETTES[key] || CARD_PALETTES.emerald;
}

// Material specific exact mapping as requested by user
export const MATERIAL_THEME_MAP: Record<string, string> = {
  // Aluminium
  'aluminium-profiles': 'blue',
  'aluminium-sheets': 'purple',
  'aluminium-frames': 'cyan',
  'aluminium-pipes': 'teal',
  'aluminium-wire': 'yellow',
  // Copper & Brass
  'copper-scrap': 'orange',
  'copper-wire': 'copper',
  'copper-strips': 'orange',
  'brass-scrap': 'yellow',
  // Iron & Steel
  'iron-scrap': 'slate',
  'steel-scrap': 'zinc',
  'stainless-steel': 'slate',
  'stainless-steel-scrap': 'slate',
  'metal-pipes': 'teal',
  'metal-sheets': 'blue',
  'metal-rods': 'cyan',
  'mixed-metal': 'emerald',
  // Motors & Electrical
  'electric-motors': 'purple',
  'electric-cables': 'emerald',
  'air-conditioner-scrap': 'cyan',
  'ac-compressors': 'teal',
  'electrical-equipment': 'indigo',
  'computer-parts': 'blue',
  'printers-photocopiers': 'slate',
  'fans-fan-motors': 'orange',
  'mixed-electrical-scrap': 'rose',
  'e-waste': 'indigo',
  // Containers & Others
  'metal-cans': 'yellow',
  'old-machinery': 'orange',
  'metal-furniture': 'purple',
  'other-mixed-scrap': 'emerald',
  'glass': 'teal',
  'cans': 'yellow',
};

export function getMaterialCardTheme(materialId: string, fallbackIndex: number = 0): CardTheme {
  const key = MATERIAL_THEME_MAP[materialId] || ROTATING_PALETTE_KEYS[fallbackIndex % ROTATING_PALETTE_KEYS.length];
  return CARD_PALETTES[key] || CARD_PALETTES.emerald;
}
